### ISSUE TITLE
table 宽度没有计算分组列的宽度吧

### ISSUE THREAD

**Issue by Nokecy** [hemengke1997/useATRH#6]
https://github.com/hemengke1997/useATRH/blob/ef55c9622895e00ac8a41a4ae7ca2868140f7490/src/index.tsx#L157

@hemengke1997

**Comment by hemengke1997** [comment]
是的 之前没有做合并列的任何处理 所以宽度也没处理  我有空写一下

**Comment by hemengke1997** [comment]
搞定了 老哥  我不知道回复怎么带上我提交的链接..

**Comment by Nokecy** [comment]
可以啊，输出很强啊～～～ @hemengke1997
